#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.cmd first."
	exit
fi

if [ ! -d "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")" ]; then
	mkdir -p "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")"
fi
olddir=$(pwd)
cd "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")"

echo "Building LibDRM"
"${LIBAROMA_GCC}" -c \
  -fdata-sections -ffunction-sections -Wl,--gc-sections \
  -fPIC -DPIC ${LIBAROMA_STRIP_OBJECT} -DUSE_MMAP -D_GNU_SOURCE -DMAJOR_IN_SYSMACROS \
  \
  ${LIBAROMA_CFLAGS} \
	\
	"${LIBAROMA_BASE}/libs/drm/xf86drm.c" \
	"${LIBAROMA_BASE}/libs/drm/xf86drmMode.c" \
  -I"${LIBAROMA_BASE}/libs/drm"

cd "${olddir}"
