#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.cmd first."
	exit
fi

if [ ! -d "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")" ]; then
	mkdir -p "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")"
fi
olddir=$(pwd)
cd "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$(basename "$0")"

echo "Building MinZIP"
"${LIBAROMA_GCC}" -c \
  -fdata-sections -ffunction-sections -Wl,--gc-sections \
  -fPIC -DPIC ${LIBAROMA_STRIP_OBJECT} -Doff64_t=int64_t \
  \
  ${LIBAROMA_CFLAGS} \
	\
	"${LIBAROMA_BASE}/libs/minzip/Hash.c" \
	"${LIBAROMA_BASE}/libs/minzip/SysUtil.c" \
	"${LIBAROMA_BASE}/libs/minzip/DirUtil.c" \
	"${LIBAROMA_BASE}/libs/minzip/Inlines.c" \
	"${LIBAROMA_BASE}/libs/minzip/Zip.c" \
	\
  -I"${LIBAROMA_BASE}/libs/selinux/include" \
  -I"${LIBAROMA_BASE}/libs/zlib/src"

cd "${olddir}"
