#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

if [ ! -d "${LIBAROMA_BASE}/tools/help" ]; then
	echo "Help files not found!"
	exit
fi
if [ ! -z "$1" ] && [ -e "${LIBAROMA_BASE}/tools/help/$1.txt" ]; then
	cat "${LIBAROMA_BASE}/tools/help/$1.txt"
else 
	cat "${LIBAROMA_BASE}/tools/help/aromahelp.txt"
fi
