#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

if [ "$1" = "/?" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	aromahelp $(basename "$0")
	exit
fi

if [ "$1" =  "all" ]; then
# delete all built targets
	echo "Clearing built libraries for all targets"
	if [ -d "${LIBAROMA_BASE}/out/libs" ]; then
		rm -rf "${LIBAROMA_BASE}/out/libs"
	fi
elif [ ! -z "$1" ]; then
# delete built files for specified library
	echo "Clearing built libraries for $1 library (${LIBAROMA_TARGET_NAME})"
	if [ -d "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$1" ]; then
		rm -rf "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/$1"
	fi
else
# by default, delete built files for current architecture
	echo "Clearing built libraries for ${LIBAROMA_TARGET_NAME}"
	if [ -d "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}" ]; then
		rm -rf "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}"
	fi
fi

exit
