#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

#if parameters are passed, check them
if [ ! -z "$1" ]; then
	#if parameter is valid library name, build it
	if [ -e "${LIBAROMA_BASE}/tools/linux/libs/$1" ]; then
		sh "${LIBAROMA_BASE}/tools/linux/libs/$1"
		exit
	#otherwise, show help for this command
	else
		echo "Invalid library name: $1"
		aromahelp $(basename "$0")
		exit
	fi
fi

if [ "${LIBAROMA_BUILD_DRM}" = "1" ]; then
sh "${LIBAROMA_BASE}/tools/linux/libs/drm"
fi
sh "${LIBAROMA_BASE}/tools/linux/libs/freetype"
if [ "${LIBAROMA_BUILD_HARFBUZZ}" = "1" ]; then
sh "${LIBAROMA_BASE}/tools/linux/libs/harfbuzz"
fi
if [ "${LIBAROMA_BUILD_JPEG}" = "1" ]; then
sh "${LIBAROMA_BASE}/tools/linux/libs/jpeg"
fi
if [ "${LIBAROMA_BUILD_MINUI}" = "1" ]; then
sh "${LIBAROMA_BASE}/tools/linux/libs/minui"
fi
sh "${LIBAROMA_BASE}/tools/linux/libs/minzip"
sh "${LIBAROMA_BASE}/tools/linux/libs/png"
sh "${LIBAROMA_BASE}/tools/linux/libs/ucdn"
sh "${LIBAROMA_BASE}/tools/linux/libs/zlib"

exit
