#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

if [ "$1" = "/?" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	aromahelp $(basename "$0")
	exit
fi

if [ ! -d "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/aromart" ]; then
	mkdir -p "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/aromart"
fi
olddir=$(pwd); cd "${LIBAROMA_BASE}/out/libs/${LIBAROMA_TARGET_NAME}/aromart"

echo "Building Libaroma runtime${LIBAROMA_DEBUG_SUFFIX}"
"${LIBAROMA_GCC}" -c \
  -fdata-sections -ffunction-sections -Wl,--gc-sections \
  -fPIC -DPIC -lstdc++ ${LIBAROMA_STRIP_OBJECT} \
  \
  ${LIBAROMA_CFLAGS} \
	"${LIBAROMA_BASE}/src/aromart/aromart_app.c" \
	"${LIBAROMA_BASE}/src/aromart/aromart_core.c" \
	"${LIBAROMA_BASE}/src/aromart/aromart_driver.c" \
	"${LIBAROMA_BASE}/src/aromart/aromart_messaging.c" \
	"${LIBAROMA_BASE}/src/aromart/aromart_sysui.c" \
	\
  -I"${LIBAROMA_BASE}/include" \
  -I"${LIBAROMA_BASE}/src"

cd "${olddir}"
