#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

if [ -z "$1" ] || [ "$1" = "/?" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	aromahelp $(basename "$0")
	exit
fi

if [ "$2" != "r" ] ; then
	sh ${LIBAROMA_BASE}/tools/linux/mkapp $1
fi

target_name="$1-${LIBAROMA_TARGET_NAME}"
if [ ! -e "${LIBAROMA_BASE}/out/bin/${target_name}" ]; then
	echo "Could not find ${target_name} at bin folder! Maybe it didn't build successfully?"
	exit
fi
echo "Going to run ${target_name} on device (recovery mode)"
echo "Waiting for device in recovery mode"
adb wait-for-recovery
adb push "${LIBAROMA_BASE}/out/bin/${target_name}" /tmp
if [ -e "${LIBAROMA_BASE}/apps/$1/zip/res.zip" ]; then
	adb push "${LIBAROMA_BASE}/apps/$1/zip/res.zip" /tmp/res.zip
fi
adb shell chmod 0755 "/tmp/${target_name}"
adb shell pkill -19 recovery
if [ "${LIBAROMA_DEBUG_ENABLED}" = "1" ]; then
	if [ -e "${LIBAROMA_GDB}" ]; then
		echo "Pushing GDB to /sbin..."
		adb shell mount -o remount,rw /
		adb push "${LIBAROMA_GDB}" /sbin/gdb
		adb shell chmod 0755 /sbin/gdb
		adb shell mkdir /bin
		adb shell ln -s /sbin/sh /bin/sh
		adb shell gdb -ex run --args "/tmp/${target_name}" 0 0 /tmp/res.zip
	else
		adb shell "/tmp/${target_name}" 0 0 /tmp/res.zip
	fi
else
	adb shell "/tmp/${target_name}" 0 0 /tmp/res.zip
fi
adb shell pkill -18 recovery

exit
