#!/bin/sh

if [ -z "${LIBAROMA_BASE}" ]; then
	echo "Libaroma environment not set, please run envsetup.sh first."
	exit
fi

if [ -z "$1" ] || [ "$1" = "/?" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	aromahelp $(basename "$0")
	exit
fi

if [ "$2" != "r" ] ; then
	sh ${LIBAROMA_BASE}/tools/linux/mkapp $1
fi

target_name="$1-${LIBAROMA_TARGET_NAME}"
if [ ! -e "${LIBAROMA_BASE}/out/bin/${target_name}" ]; then
	echo "Could not find ${target_name} at bin folder! Maybe it didn't build successfully?"
	exit
fi
echo "Going to run ${target_name}"
if [ "${LIBAROMA_DEBUG_ENABLED}" = "1" ]; then
	if [ -e "${LIBAROMA_GDB}" ]; then
		"${LIBAROMA_GDB}" -ex run --args "${LIBAROMA_BASE}/out/bin/${target_name}" 0 0 "${LIBAROMA_BASE}/apps/$1/zip/res.zip"
	else
		"${LIBAROMA_BASE}/out/bin/${target_name}" 0 0 "${LIBAROMA_BASE}/apps/$1/zip/res.zip"
	fi
else
	"${LIBAROMA_BASE}/out/bin/${target_name}" 0 0 "${LIBAROMA_BASE}/apps/$1/zip/res.zip"
fi
